"""update docs table

Revision ID: 1608693e345e
Revises: 0070d541b018
Create Date: 2025-07-22 17:25:40.380261

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1608693e345e'
down_revision: Union[str, Sequence[str], None] = '0070d541b018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    doc_type_enum = postgresql.ENUM('CV', name='doctype', create_type=False)
    doc_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('docs', sa.Column('type', doc_type_enum, nullable=False))

    doc_format_enum = postgresql.ENUM('PDF', 'TXT', name='docformat', create_type=False)
    doc_format_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('docs', sa.Column('format', doc_format_enum, nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs', 'format')
    op.drop_column('docs', 'type')
    op.drop_column('docs', 'name')
    # ### end Alembic commands ###
