"""update docs table

Revision ID: 1608693e345e
Revises: 0070d541b018
Create Date: 2025-07-22 17:25:40.380261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1608693e345e'
down_revision: Union[str, Sequence[str], None] = '0070d541b018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('docs', sa.Column('type', sa.Enum('CV', name='doctype'), nullable=False))
    op.add_column('docs', sa.Column('format', sa.Enum('PDF', 'TXT', name='docformat'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs', 'format')
    op.drop_column('docs', 'type')
    op.drop_column('docs', 'name')
    # ### end Alembic commands ###
