apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: llm-minikube-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/MTB90/llm-minikube
      revision: main
      directories:
      - path: gitops/apps/*/overlays/minikube
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{index .path.segments 4}}'
    spec:
      project: llm
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/MTB90/llm-minikube
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'llm'
