apiVersion: v1
kind: Service
metadata:
  name: minio-web
spec:
  selector:
    app: minio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web
    - name: https
      protocol: TCP
      port: 443
      targetPort: web

---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
spec:
  selector:
    app: minio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: api
    - name: https
      protocol: TCP
      port: 443
      targetPort: api
