apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: minio-secret
    literals:
      - MINIO_ROOT_USER=minioAccessKey
      - MINIO_ROOT_PASSWORD=minioSecretKey

resources:
  - ../../base
