services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: password
    ports:
    - 54321:5432

  migration:
    image: cv-platform-backend:latest
    environment:
      CV_BACKEND_DB_HOST: db:5432
      CV_BACKEND_DB_NAME: platform
      CV_BACKEND_DB_USER: platform
      CV_BACKEND_DB_PASS: password
      CV_BACKEND_MINIO_PORT: 9000
      CV_BACKEND_MINIO_ENDPOINT: minio
      CV_BACKEND_MINIO_ACCESS_KEY: minioAccessKey
      CV_BACKEND_MINIO_SECRET_KEY: minioSecretKey
      CV_BACKEND_MINIO_BUCKET_NAME: minio-platform-bucket
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head'
    depends_on:
      - db

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - 9090:9090
      - 9000:9000
    command: [ "server", "--console-address", ":9090", "/data" ]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
