services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: password
    ports:
    - 54321:5432

  migration:
    build: .
    environment:
      CV_BACKEND_DB_HOST: db:5432
      CV_BACKEND_DB_NAME: platform
      CV_BACKEND_DB_USER: platform
      CV_BACKEND_DB_PASS: password
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head'
    depends_on:
      - db
