services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: password
    ports:
    - 54321:5432

  migration:
    build: .
    environment:
      CV_BACKEND_DB_HOST: db:5432
      CV_BACKEND_DB_NAME: platform
      CV_BACKEND_DB_USER: platform
      CV_BACKEND_DB_PASS: password
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head'
    depends_on:
      - db

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - 9090:9090
      - 9000:9000
    command: [ "server", "--console-address", ":9090", "/data" ]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
