apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-api
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-api
    spec:
      containers:
      - image: quay.io/redhatworkshops/welcome-php
        name: backend-api
        resources: {}
status: {}
