name: Main CI
on:
  push:
    branches:
      - main

jobs:
  platform-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install-requirements
        working-directory: platform/backend
        run: |
          make pip-install
          make pip-install-test

      - name: code-test
        working-directory: platform/backend
        run: make code-test

      - name: unit-test
        working-directory: platform/backend
        run: make unit-test

  platform-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate tag version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          PRERELEASE: true
          DRY_RUN: true

  platform-push:
    needs: [ platform-tag, platform-tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build-image
        working-directory: platform/backend
        run: make build-image
